/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as paymentGatewaySol from "./PaymentGateway.sol";
export * as paymentProcessorSol from "./PaymentProcessor.sol";
