/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IChilizDex } from "./IChilizDex";
export type { IERC20 } from "./IERC20";
export type { IMailbox } from "./IMailbox";
export type { PaymentProcessor } from "./PaymentProcessor";
