/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHyperlaneWarpRoute,
  IHyperlaneWarpRouteInterface,
} from "../../../../src/contracts/PaymentGateway.sol/IHyperlaneWarpRoute";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "destination",
        type: "uint32",
      },
      {
        internalType: "bytes32",
        name: "recipient",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferRemote",
    outputs: [
      {
        internalType: "bytes32",
        name: "messageId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IHyperlaneWarpRoute__factory {
  static readonly abi = _abi;
  static createInterface(): IHyperlaneWarpRouteInterface {
    return new Interface(_abi) as IHyperlaneWarpRouteInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHyperlaneWarpRoute {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IHyperlaneWarpRoute;
  }
}
