/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as paymentGatewaySol from "./PaymentGateway.sol";
export type { paymentGatewaySol };
import type * as paymentProcessorSol from "./PaymentProcessor.sol";
export type { paymentProcessorSol };
