/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IChilizDex,
  IChilizDexInterface,
} from "../../../../src/contracts/PaymentProcessor.sol/IChilizDex";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "_swap",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "chzAmount",
        type: "uint256",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "tokens",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IChilizDex__factory {
  static readonly abi = _abi;
  static createInterface(): IChilizDexInterface {
    return new Interface(_abi) as IChilizDexInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IChilizDex {
    return new Contract(address, _abi, runner) as unknown as IChilizDex;
  }
}
