/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMailbox,
  IMailboxInterface,
} from "../../../../src/contracts/PaymentProcessor.sol/IMailbox";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "metadata",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "process",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMailbox__factory {
  static readonly abi = _abi;
  static createInterface(): IMailboxInterface {
    return new Interface(_abi) as IMailboxInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IMailbox {
    return new Contract(address, _abi, runner) as unknown as IMailbox;
  }
}
